.vscode/launch.json, server/package.json, server/src/modules/data/usecases/getTransformationStats/data/dataEffectif.schema.ts, server/src/modules/data/usecases/getTransformationStats/data/dataEffectifAcademie.ts, server/src/modules/data/usecases/getTransformationStats/data/dataEffectifDepartement.ts, server/src/modules/data/usecases/getTransformationStats/data/dataEffectifRegion.ts, server/src/modules/data/usecases/getTransformationStats/getTransformationStats.test.ts, server/src/modules/data/usecases/getTransformationStats/getTransformationStats.usecase.ts
- Refactoring de la méthode formatResult
- Ajout des fichiers contenant les effectifs en fonction du niveau de diplôme 
- Ajout de debugging dans vscode
=> Feature:  Taux de transformation comprenant le niveau de diplôme

ui/app/(wrapped)/intentions/saisie/intentionForm/IntentionForm.tsx
=> Retirer le libelle indiquant la période pour le projet de demande

ui/app/(wrapped)/components/LandingFooter.tsx
=> feat: ajout mail contact page d'accueil

server/src/modules/data/usecases/getDataForPanoramaDepartement/dependencies.ts, server/src/modules/data/usecases/getDataForPanoramaEtablissement/dependencies.ts, server/src/modules/data/usecases/getDataForPanoramaRegion/dependencies.ts, server/src/modules/data/usecases/getDepartement/getDepartement.query.ts, server/src/modules/data/usecases/getEtablissements/dependencies.ts, server/src/modules/data/usecases/getFormations/dependencies.ts, server/src/modules/data/usecases/getRegion/getRegion.query.ts, server/src/modules/data/utils/tauxPression.ts
**Suppression du taux de pression pour les BTS dans la console et les panoramas**
=> feat: suppression du taux de pression des BTS

server/src/modules/data/usecases/getScopedTransformationStats/dependencies.ts
Le filtre Diplôme contient actuellement 21 diplomes , en faisant l'union avec les diplomes qui sont dans le constat de rentré on en obtient maintenant 23
| Code       | Number |
|------------|--------|
| MC         | 010    |
| DSAA-1     | 140    |
| DIV-1      | 160    |
| DNMADE     | 241    |
| DIV-2      | 260    |
| BTS        | 320    |
| DMA        | 321    |
| BTSA       | 323    |
| DIV-3      | 360    |
| FCIL N-3   | 381    |
| BAC PRO    | 400    |
| BMA        | 401    |
| BAC PRO AG | 403    |
| BT         | 420    |
| BAC TECHNO | 430    |
| BP         | 450    |
| DIV-4      | 460    |
| FCIL N-4   | 481    |
| CAP        | 500    |
| CAPA       | 503    |
| DIV-5      | 560    |
| FCIL N-5   | 581    |
| 1E CYC.GEN | 670    |
=> fix: correction de la liste des diplomes dans le filtre

server/src/modules/data/usecases/getDataForPanoramaEtablissement/dependencies.ts, server/src/modules/data/usecases/searchEtablissement/findManyInDataEtablissementQuery.dep.ts, server/src/modules/intentions/usecases/getDemandes/getDemandes.query.ts, server/src/modules/intentions/usecases/searchDiplome/findManyInDataFormationQuery.dep.ts, server/src/modules/intentions/usecases/searchDiplome/searchDiplome.schema.ts, ui/app/(wrapped)/intentions/saisie/components/CfdAutocomplete.tsx, ui/app/(wrapped)/panorama/etablissement/[uai]/page.tsx
Fix de la recherche des établissements non ouverts dans le panorama :
Fix de la recherche des options BTS dans le formulaire de collecte des demandes :
=> Fix panorama etab non ouvert

server/public/files/diplomesProfessionnels.csv, server/src/modules/import/usecases/importDataFormations/importDataFormations.usecase.ts
=> fix: normalize cpc, cpcsecteur, cpcsoussecteur

package.json
Suite à la modification du script `yarn dev:ui` et `yarn dev:server` je dois modifier la commande `yarn dev`
=> chore: correction du script dev du package de l'application

server/src/modules/data/usecases/getDepartement/getDepartement.query.ts, server/src/modules/data/usecases/getRegion/getRegion.query.ts, server/src/modules/data/utils/tauxPression.ts
Correction de la valeur des effectifs lié à un group by lors de la mise a jour du taux de pression des bts
=> fix: correction groupby du taux de pression des BTS

server/src/modules/import/usecases/importFormationEtablissement/steps/importEtablissement/findGeoloc.dep.ts
fix: latitude longitude pour les coordonnées des etablissements venant de la ban
=> fix: latitude longitude pour les coordonnées des etablissements venant de la ban

.gitignore, server/.gitignore
=> fix: conserve le répertoire logs dans git

ui/app/(wrapped)/intentions/pilotage/components/IndicateursClesSection.tsx, ui/app/(wrapped)/intentions/pilotage/components/VueTauxTransformationSection.tsx
=> fix: typo page intentions pilotage

ui/app/(wrapped)/panorama/etablissement/components/analyse-detaillee/dashboard/Dashboard.tsx, ui/components/GlossaireShortcut.tsx, ui/components/Graph.tsx, ui/components/TooltipIcon.tsx, ui/theme/Tooltip.theme.ts
=> chore: augmentation de la taille de police des tooltips

server/src/modules/data/usecases/getHeaderEtablissement/getHeaderEtablissement.schema.ts, ui/app/(wrapped)/panorama/etablissement/components/header/components/Coordonnees.tsx
Modification du champ adresse pour qu'il soit optionnel dans le header de la page etab
=> fix: champ adresse optionnel 

ui/app/(wrapped)/auth/login/components/AlertPerdir.tsx
=> chore (connexion): changement du message perdir

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml
https://www.metabase.com/docs/latest/releases
=> chore (metabase): update

reverse_proxy/dev/nginx/templates/conf.d/default.conf.template, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/observationsSection/ObservationsSection.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/observationsSection/filesSection/FilesField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/observationsSection/filesSection/FilesSection.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/observationsSection/filesSection/UploadField.tsx, ui/app/(wrapped)/intentions/perdir/synthese/[numero]/main/synthese/SyntheseSection.tsx, ui/app/(wrapped)/intentions/perdir/synthese/[numero]/main/synthese/files/FilesSection.tsx, ui/app/(wrapped)/intentions/perdir/synthese/[numero]/main/synthese/files/types.ts
=> feat(synthese): ajout des pièces jointes

reverse_proxy/app/nginx/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/observationsSection/filesSection/UploadField.tsx
Mise à jour des règles owasp pour pouvoir ajouter les fichiers .doc à l'application
=> chore: ajout de l'upload des fichiers .doc

server/src/modules/demandes/usecases/getDemandes/getDemandes.query.ts, server/src/modules/demandes/usecases/importDemande/dependencies/hasAlreadyBeenImported.ts, server/src/modules/intentions/usecases/getIntentions/getIntentions.query.ts, server/src/modules/intentions/usecases/importIntention/dependencies/createIntention.dep.ts, server/src/modules/intentions/usecases/importIntention/dependencies/getIntentionWithMetadata.ts, server/src/modules/intentions/usecases/importIntention/dependencies/hasAlreadyBeenImported.ts, server/src/modules/intentions/usecases/importIntention/importIntention.usecase.ts, shared/security/permissions.ts, ui/app/(wrapped)/intentions/perdir/saisie/page.client.tsx, ui/app/(wrapped)/intentions/saisie/page.client.tsx
Mise à jour des droits d'un pilote region
Correction duplication pour demande 
Correction duplication pour intentions
=> fix: correction de la duplication d'une demande / intention

ui/app/(wrapped)/intentions/perdir/saisie/components/CapaciteField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/internatEtRestaurationSection/AugmentationCapaciteAccueilHebergementPlacesField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/internatEtRestaurationSection/AugmentationCapaciteAccueilRestaurationPlacesField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/formationRHSection/NbFormationRHField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/professeurAssocieRHSection/NbProfesseurAssocieRHField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/reconversionRHSection/NbReconversionRHField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/recrutementRHSection/NbRecrutementRHField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/travauxEtEquipementsSection/AchatEquipementCoutField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/travauxEtEquipementsSection/TravauxAmenagementCoutField.tsx, ui/app/(wrapped)/intentions/saisie/components/CapaciteField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/formationRHSection/NbFormationRHField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/professeurAssocieRHSection/NbProfesseurAssocieRHField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/reconversionRHSection/NbReconversionRHField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/recrutementRHSection/NbRecrutementRHField.tsx
Force la saisie de nombre entier dans le champ recrutementRH du formulaire
=> fix(formulaire): correction saisie décimal recrutement dans formulaire

ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/professeurAssocieRHSection/NbProfesseurAssocieRHField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/rhSection/recrutementRHSection/NbRecrutementRHField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/professeurAssocieRHSection/NbProfesseurAssocieRHField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/rhSection/recrutementRHSection/NbRecrutementRHField.tsx
Correction du message à afficher dans les formulaires pour les saisies des recrutements
=> fix(formulaire): fix des messages pour le recrutement dans les formulaires

ui/app/(wrapped)/admin/users/CreateUser.tsx
fix de la selection par défaut de la region pour les admin region qui essayent d'ajouter un nouvel utilisateur
=> fix(admin): fix de la saisie d'une region pour les admins region

ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/travauxEtEquipementsSection/AchatEquipementCoutField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/travauxEtEquipementsSection/TravauxAmenagementCoutField.tsx
Modification de la regex de control de l'input pour les couts sur le formulaire. La regex renvoyé une erreur auparavant
=> fix(formulaire): modification de la regex pour les couts

ui/app/(wrapped)/intentions/perdir/saisie/[numero]/client.tsx, ui/app/(wrapped)/intentions/perdir/saisie/page.client.tsx, ui/app/(wrapped)/intentions/perdir/saisie/utils/canEditIntention.ts, ui/app/(wrapped)/intentions/perdir/synthese/[numero]/main/MainSection.tsx
Un perdir peut modifier seulement les intentions qui ont le statut brouillon / proposition / dossier incomplet
=> fix(permissions): modifications des droits des perdirs à modifier une intention

server/src/migrations/index.ts, server/src/migrations/migration_1721813177511.ts
migration contenant  la mise à jour eds capacité pour les intentions et demandes
=> data: mise à jour eds capacité pour les intentions et demandes

server/src/migrations/index.ts, server/src/migrations/migration_1721827020716.ts
migration des capacité avec une désactivation des triggers
=> data(coloration): migration capacite scolaire et apprentissage

server/src/db/schema.ts, server/src/migrations/index.ts, server/src/migrations/migration_1720190144765.ts, server/src/modules/core/index.ts, server/src/modules/core/usecases/isMaintenance/isMaintenance.query.ts, server/src/modules/core/usecases/isMaintenance/isMaintenance.route.ts, server/src/modules/core/usecases/isMaintenance/isMaintenance.schema.ts, server/src/modules/core/usecases/isMaintenance/isMaintenance.usecase.ts, ui/app/(wrapped)/components/Header.tsx, ui/app/(wrapped)/components/MaintenancePage.tsx, ui/app/(wrapped)/layout.tsx
Version v0 de la page de maintenance se déployant uniquement via un flag en base, version allégée en attente d'une version plus aboutie au retour de Gaëtan
=> feat: ajout d'une page de maintenance se déployant via un flag en DB

server/src/modules/core/usecases/createUser/createUser.usecase.ts, shared/security/permissions.ts, ui/app/(wrapped)/admin/roles/const.ts, ui/app/(wrapped)/intentions/utils/roleUtils.tsx
=> feat (role-invite): Création du rôle invité

server/src/db/schema.ts, server/src/migrations/index.ts, server/src/migrations/migration_1724142453681.ts, server/src/modules/import/usecases/importLienEmploiFormation/importLienEmploiFormation.usecase.ts, ui/tsconfig.json
Ajout de 3 nouvelles colonnes à la table Rome : 
* Transition Ecologique 
* Transition Numérique 
* Transition Démographique
=> feat(rome): ajout des flags Transition Ecologique/Numerique/Demographique à la table Rome

ui/app/(wrapped)/admin/users/page.tsx, ui/app/(wrapped)/console/etablissements/page.tsx, ui/app/(wrapped)/console/formations/page.tsx, ui/app/(wrapped)/intentions/perdir/saisie/components/Header.tsx, ui/app/(wrapped)/intentions/pilotage/components/QuadrantSection.tsx, ui/app/(wrapped)/intentions/restitution/page.tsx, ui/app/(wrapped)/intentions/saisie/components/Header.tsx, ui/app/(wrapped)/panorama/etablissement/components/carto/components/ExportList.tsx, ui/utils/formatExportFilename.ts
Renommage des fichiers d'export pour : 
- console formation
- console etablissement 
- restitution
- boite de reception expe
- boite de reception
=> feat(renommage): renommage des fichiers d'export

server/src/modules/demandes/usecases/countDemandes/countDemandes.query.ts, server/src/modules/demandes/usecases/countDemandes/countDemandes.route.ts, server/src/modules/demandes/usecases/countDemandes/countDemandes.schema.ts, server/src/modules/intentions/usecases/countIntentions/countIntentions.query.ts, server/src/modules/intentions/usecases/countIntentions/countIntentions.route.ts, server/src/modules/intentions/usecases/countIntentions/countIntentions.schema.ts, ui/app/(wrapped)/intentions/perdir/saisie/components/MenuIntention.tsx, ui/app/(wrapped)/intentions/perdir/saisie/page.client.tsx, ui/app/(wrapped)/intentions/saisie/components/MenuIntention.tsx
Correction de l'affichage du compteur dans la boite de reception pour le formulaire expe et formulaire. 
+ Correction du clique sur le bouton suivie dans le formulaire expe
=> fix: correction compteur boite de reception formulaire

server/src/modules/intentions/usecases/getIntentions/deps/getIntentions.dep.ts, server/src/modules/intentions/usecases/getIntentions/getIntentions.schema.ts, ui/app/(wrapped)/intentions/perdir/components/AvisStatutTag.tsx, ui/app/(wrapped)/intentions/perdir/saisie/INTENTIONS_COLUMNS.ts, ui/app/(wrapped)/intentions/perdir/saisie/components/AvisTags.tsx, ui/app/(wrapped)/intentions/perdir/saisie/components/Header.tsx, ui/app/(wrapped)/intentions/perdir/saisie/components/ProgressSteps.tsx, ui/app/(wrapped)/intentions/perdir/saisie/page.client.tsx, ui/app/(wrapped)/intentions/perdir/saisie/types.ts
Affichage des avis dans la boite de reception du formulaire expe
=> feat: affichage des avis dans la boite de reception expe

.infra/ansible/env.ini
Mise à jour de l'IP de la recette 1
=> chore(recette): mise à jour de l'adresse ip de la recette 1

ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/typeDemandeSection/RentreeScolaireField.tsx, ui/app/(wrapped)/intentions/perdir/saisie/intentionForm/typeDemandeSection/TypeDemandeField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/typeDemandeSection/RentreeScolaireField.tsx, ui/app/(wrapped)/intentions/saisie/intentionForm/typeDemandeSection/TypeDemandeField.tsx
la capacité ne doit pas être remise à zero si la rentrée scolaire est changé
=> fix(capacite): capacité du formulaire

server/src/migrations/index.ts, server/src/migrations/migration_1726811693181.ts, server/src/modules/core/usecases/createUser/createUser.schema.ts, server/src/modules/core/usecases/createUser/createUser.usecase.ts, server/src/modules/core/usecases/editUser/editUser.schema.ts, server/src/modules/core/usecases/login/login.schema.ts, server/src/modules/core/usecases/login/login.usecase.ts, server/src/modules/core/usecases/redirectDne/redirectDne.usecase.ts, server/src/modules/core/usecases/sendResetPassword/sendResetPassword.schema.ts, server/src/modules/core/usecases/sendResetPassword/sendResetPassword.usecase.ts
- mise à jour en DB de tous les emails pour qu'ils passent en lowercase 
- passage en lowercase des emails qui sont saisis dans le schema
=> fix(auth): mise à jour de la recherche des emails en lowercase

server/package.json, shared/package.json, ui/package.json, yarn.lock
=> chore(axios): upgrade axios package

server/src/modules/data/usecases/searchDiplome/searchDiplome.query.ts, server/src/modules/demandes/usecases/countDemandes/countDemandes.query.ts, server/src/modules/demandes/usecases/getDemandes/deps/getDemandes.dep.ts, server/src/modules/intentions/usecases/countIntentions/countIntentions.query.ts, server/src/modules/intentions/usecases/getIntentions/deps/getIntentions.dep.ts, ui/app/(wrapped)/intentions/perdir/saisie/components/Header.tsx, ui/app/(wrapped)/intentions/saisie/components/Header.tsx
- mise à jour des champs de recherche pour la boite de reception des demandes et intentions
=> feat(recherche): mise à jour des champs de recherche pour la boite de reception

ui/app/(wrapped)/cgu/page.tsx, ui/app/(wrapped)/components/LandingFooter.tsx, ui/app/(wrapped)/components/MinimalFooter.tsx, ui/app/(wrapped)/components/Nav.tsx, ui/app/(wrapped)/politique-de-confidentialite/page.tsx
1. Ajout du lien des CGU dans le foot
2. Mise à jour de la page Notion des CGU
3. Ajout du lien de la politique de confidentialité
4. Ajout de la page politique de confidentialité
5. Suppression du lien des ressources de la barre de navigation
6. Ajout du lien des ressources dans le footer
=> feat: mise à jour des liens du footer

server/src/modules/core/usecases/createUser/createUser.test.ts, server/src/modules/core/usecases/createUser/createUser.usecase.ts, server/src/modules/core/usecases/sendResetPassword/findUserQuery.dep.ts, server/src/modules/core/usecases/sendResetPassword/sendResetPassword.test.ts, server/src/modules/core/usecases/sendResetPassword/sendResetPassword.usecase.ts, ui/app/(wrapped)/admin/users/CreateUser.tsx, ui/app/(wrapped)/auth/mot-de-passe-oublie/askResetPasswordForm.tsx, ui/utils/apiError.ts
Création d'un message d'erreur pour les utilisateurs SSO qui veulent réinitialiser leur mot de passe
=> fix: réinitilisation du mot de passe des utilisateurs SSO

server/src/modules/data/usecases/getDataForPanoramaRegion/dependencies/getTauxIJ.dep.ts, server/src/modules/data/usecases/getDataForPanoramaRegion/dependencies/index.ts, server/src/modules/data/usecases/getDataForPanoramaRegion/getDataForPanoramaRegion.schema.ts, server/src/modules/data/usecases/getDataForPanoramaRegion/getDataForPanoramaRegion.usecase.ts, ui/app/(wrapped)/panorama/components/IndicateursSection/IndicateursSection.tsx, ui/app/(wrapped)/panorama/components/TauxInserJeunesSection/TauxInserJeunesSection.tsx, ui/app/(wrapped)/panorama/region/[codeRegion]/page.tsx, ui/app/(wrapped)/panorama/types.ts
Ajout d'indicateurs IJ dans le parorama régional
=> feat(panorama): ajout des indicateurs IJ dans le panorama regional

server/src/modules/data/usecases/getDataForPanoramaRegion/dependencies/getTauxIJ.dep.ts
=> fix: requête affichage des taux ij dans le panoram region

ui/app/(wrapped)/panorama/components/IndicateursSection/IndicateursSection.tsx, ui/components/GraphWrapper.tsx
=> fix (mini-graph): Round number homogenization

ui/app/(wrapped)/intentions/perdir/synthese/[numero]/main/synthese/SyntheseSection.tsx, ui/app/(wrapped)/intentions/synthese/[numero]/main/synthese/SyntheseSection.tsx, ui/app/(wrapped)/intentions/utils/motifDemandeUtils.tsx
=> feat (motif-synthese-intention): Ajout de l'autre motif dans la synthèse

server/src/modules/data/usecases/getFormationIndicateurs/dependencies/getTauxIJ.dep.ts, ui/app/(wrapped)/domaine-de-formation/[codeNsf]/components/FormationSection/Tabs/IndicateursTab/DevenirBarGraph.tsx
Petit fix de l'ordre des millesimes des taux IJ
=> fix(formations): mise à jour de l'ordre des millesimes des taux IJ

.talismanrc, shared/security/__tests__/permissions.test.ts, shared/utils/__tests__/emailRegex.test.ts, shared/utils/__tests__/escapeString.test.ts, shared/utils/__tests__/isValidUrl.test.ts, shared/utils/emailRegex.ts, shared/utils/isValidUrl.ts
1. Ajout de tests dans le shared
2. Modification de la regex de validation des emails
3. Modification de la méthode de validation des urls
=> test(shared): ajout de tests dans les utils de shared

ui/app/(wrapped)/domaine-de-formation/[codeNsf]/components/FormationSection/Tabs/EtablissementsTab/ExportListEtablissements.tsx, ui/app/(wrapped)/domaine-de-formation/[codeNsf]/components/FormationSection/Tabs/IndicateursTab/ExportListIndicateurs.tsx, ui/app/(wrapped)/domaine-de-formation/[codeNsf]/context/formationContext.tsx, ui/utils/handleMetadata.ts
Ajout d'évènements Plausible à la page domaine de formation
=> fix(plausible): page domaine de formation

ui/app/(wrapped)/intentions/perdir/saisie/components/MenuBoiteReception.tsx, ui/app/(wrapped)/intentions/saisie/components/MenuBoiteReception.tsx
Modification de l'état des boutons de création d'une nouvelle demande / intention
=> fix: modification du statut desactivé des boutons des formulaires

server/src/modules/core/services/dneClient/dneClient.ts
À merge et déployer le 26/02 à 12h
=> feat(dneIssuer-update): mise à jour de l'Issuer OpenID de la DNE

ui/app/(wrapped)/components/DefinitionTauxTransfoModal.tsx
=> fix: typo modal page pilotage

ui/app/(wrapped)/domaine-de-formation/[codeNsf]/components/FormationSection/Tabs/EtablissementsTab/components/EtablissementItemContent.tsx, ui/app/(wrapped)/intentions/restitution/ConsoleSection/HeadLineContent.tsx, ui/app/(wrapped)/panorama/etablissement/components/carto/components/ListEtablissementsProches/components/CustomListItem.tsx
2 typo + un fix d'affichage des tooltips dans la page de restit
=> fix: fix css et typo
